apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lyxbmui1p-python
  janus-idp.io/tekton: lyxbmui1p-python
  backstage.io/kubernetes-id: lyxbmui1p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lyxbmui1p-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
